// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeebhbutrxqqtezmvdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZWJoYnV0cnhxcXRlem12ZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzQxMDMsImV4cCI6MjA1NDExMDEwM30.uP6xBdqLr6SM4guP7IbTl6YVHz7EYP29RARlTt0q1D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);